name: Release

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g., 1.2.3 or v1.2.3) - Leave empty to auto-increment patch"
        required: false
      prerelease:
        description: "Mark release as prerelease"
        type: boolean
        required: false
        default: false

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build with Vite
        run: npm run build

      - name: Verify build output
        run: |
          echo "Build output verification:"
          ls -la dist/
          echo ""
          echo "Checking bundle sizes:"
          du -h dist/*.mjs dist/*.umd.js

      - name: Determine version
        id: version
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            echo "Fetching latest release from assistos-sdk-releases..."
            LATEST_TAG=$(gh release list --repo AssistOS-AI/assistos-sdk-releases --limit 1 --json tagName --jq '.[0].tagName // "v0.0.0"' || echo "v0.0.0")
            echo "Latest tag: $LATEST_TAG"
            
            VERSION_WITHOUT_V=${LATEST_TAG#v}
            IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION_WITHOUT_V"
            
            PATCH=$((PATCH + 1))
            VERSION="${MAJOR}.${MINOR}.${PATCH}"
            echo "Auto-incremented version: $VERSION"
          fi
          
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Checkout releases repository
        uses: actions/checkout@v4
        with:
          repository: AssistOS-AI/assistos-sdk-releases
          token: ${{ secrets.GIT_TOKEN }}
          path: assistos-sdk-releases

      - name: Copy bundles to releases repository
        run: |
          cp -f dist/assistos-sdk.mjs assistos-sdk-releases/assistos-sdk.mjs
          cp -f dist/assistos-sdk.umd.js assistos-sdk-releases/assistos-sdk.umd.js
          echo "Bundles copied to releases repository:"
          ls -la assistos-sdk-releases/

      - name: Compute tag name
        id: tag
        run: |
          VERSION='${{ steps.version.outputs.version }}'
          if [[ "$VERSION" =~ ^v ]]; then TAG="$VERSION"; else TAG="v$VERSION"; fi
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Commit, tag, and push to releases repository
        working-directory: assistos-sdk-releases
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assistos-sdk.mjs assistos-sdk.umd.js
          if git diff --cached --quiet; then
            echo "No bundle changes to commit"
          else
            echo "Committing bundles for version ${{ steps.version.outputs.version }}"
            git commit -m "chore(release): add Vite bundles for ${{ steps.version.outputs.version }}"
            git tag -a "${{ steps.tag.outputs.tag }}" -m "Release ${{ steps.version.outputs.version }}"
            git push
            git push origin "${{ steps.tag.outputs.tag }}"
          fi

      - name: Create GitHub Release in releases repository
        working-directory: assistos-sdk-releases
        run: |
          gh release create "${{ steps.tag.outputs.tag }}" \
            --repo AssistOS-AI/assistos-sdk-releases \
            --title "${{ steps.version.outputs.version }}" \
            --notes "Official release for AssistOS-SDK version ${{ steps.version.outputs.version }}" \
            ${{ github.event.inputs.prerelease == 'true' && '--prerelease' || '' }} \
            assistos-sdk.mjs assistos-sdk.umd.js
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
